### ISSUE TITLE
TODO: minor improvements

### ISSUE THREAD

**Issue by vkhodygo** [andrewbaxter439/UC-DiD-analysis#3]
There should be documentation discussing naming conventions and the package structure itself, some common features are listed right below:

- [ ] rename files to remove whitespaces
- [ ] rename files to make names short and concise 
- [ ] move tests to a separate folder for clear distinction

**Comment by vkhodygo** [comment]
@andrewbaxter439 I'd like to hear your comments regarding this.

**Comment by andrewbaxter439** [comment]
Thanks Vlad, these sound helpful suggestions.

As a quick thing to explain about this repo so far, it's one half of the code in use for the DiD analysis, with the other half being composed in a safe lab. Perhaps all can be combined once finished with a code extraction request (and a long form to fill in!). So apologies that it's a bit haphazard so far.

Naming convention - will ensure use of underscores in ongoing file names. Been trying to find balance between concise and descriptive. The scripts in place so far tended to have been run once to either test or output something, and the file name is describing the process as a verb ("predicting_", "testing_" etc.). This is mostly a developed habit when I recall my past frustration trying to find the file I need for something! Very few scripts are dependent on each other, and they don't run in an order. Would there be helpful conventions for denoting the use of each script?

Testing - the scripts labelled 'testing' are currently housing code for testing things about the data, rather than testing output of functions. Would assume the latter kinds of tests would benefit from a new folder. There are few functions here at the moment though and no associated tests. Partially I'd not be sure the formal tests are needed as any function would be used a number of times in one run of the analysis and not subject to later modification?

Stata code file - put this here as a reference/comparison with other code. Not needed so have moved to a .gitignored 'reference' directory.

**Comment by vkhodygo** [comment]
I'm not sure how it works in R, my experience with functional languages is a bit limited. 

Usually you have a separate directory or a directory tree for pieces of code with similar functionality or similar meaning. 
Say, you keep statistical methods together, but you can also collect all variance or std functions in one sub-directory as well.

There is nothing wrong with naming your files like that, however, when their number reach a certain threshold you might start thinking about doing something with this.

There are various kinds of tests, data validation is important as well.  Take a [look](https://en.wikipedia.org/wiki/Software_testing) and let me know what matches your code the best. We can go from that point.
